### ISSUE TITLE
A exercise in vfa/Redblack.v does not seem provable

### ISSUE THREAD

**Issue by HuStmpHrrr** [DeepSpec/dsss18#11]
Consider following lemma:

```coq
Definition elements_property (t: tree) (cts: total_map V) : Prop :=
   forall k v,
    (In (k,v) (elements t) -> cts (int2Z k) = v) /\
    (cts (int2Z k) <> default -> In (k, cts (int2Z k)) (elements t)).
Theorem elements_relate:
  forall t cts,
  SearchTree t ->
  Abs t cts ->
  elements_property t cts.
```

This lemma does not seem provable. Specifically, the second conjunction:

```coq
 (cts (int2Z k) <> default -> In (k, cts (int2Z k)) (elements t)
```

is not provable in the case where `k` is found in the tree. In that time, the premises will look like

```coq
t = T _ l (int2Z k0) (cts (int2Z k0)) r
int2Z k0 = int2Z k
```

while the goal is

```coq
In (k, cts (int2Z k)) [(k0, cts(int2Z k0)]
```

since `int` is a postulated type, we cannot prove `k = k0`. 

For this reason, I propose to use 

```coq
cts (int2Z k) <> default -> exists k', int2Z k = int2Z k' /\ In (k', cts (int2Z k)) (elements t)
```

to be the goal instead. This new goal is weakened, such that any `k'` in the same fibre as `k` w.r.t `int2Z` will work, and I've proved this lemma with this modified goal instead.

Another way to fix it is to postulate `int2Z` is injective. However, this is quite a strong axiom to introduce (though no inconsistency introduced).

Please confirm if the original goal can be proved and if not, my proposed goal is a good idea or not. I can raise a PR if it's OK.

**Comment by HuStmpHrrr** [comment]
thank you for you fast response. PR created.

**Comment by andrew-appel** [comment]
Fixed in the sources (in the sfdev repo).
