### ISSUE TITLE
is this *) supposed to be there?

### ISSUE THREAD

**Issue by DustinWehr** [DeepSpec/dsss18#4]
https://github.com/DeepSpec/dsss18/blob/e5da53c0ab225cdb46126cc1256c132c9957fa53/lf/Induction.v#L215

**Comment by Lysxia** [comment]
It closes this comment

https://github.com/DeepSpec/dsss18/blob/e5da53c0ab225cdb46126cc1256c132c9957fa53/lf/Induction.v#L211-L215

The "fill in here" is in comments because the exercise is to write an explanation in natural language rather than code.

**Comment by DustinWehr** [comment]
With it, I get an error. Without it, everything works.

**Comment by DustinWehr** [comment]
In both CoqIDE and Sublime.

**Comment by DustinWehr** [comment]
Ah, it works without it because it makes the rest of the document a comment. Doesn't work with it because of some unrelated issue.

**Comment by DustinWehr** [comment]
@Lysxia in any case, it appears to confuse the Sublime CoqIDE syntax highlighters.

**Comment by DustinWehr** [comment]
It's a bug with nested comments in the Sublime plugin.
